### ISSUE TITLE
Bug in the stats page

### ISSUE THREAD

**Issue by statulr** [wavly/shawty#30]
Error with checking stats

To reproduce: Shorten link and click stats without testing the shortened link first

Theory: We have no static page or way to handle no stats, we should make a "We can't get stats without any links 😉 " type of page

**Comment by statulr** [comment]
<img width="536" alt="error" src="https://github.com/user-attachments/assets/03e00506-b972-4436-ad60-82e877298380">
For some reason now it semiworks but does this

**Comment by Hamza12700** [comment]
I was right, it's because when the `last_accessed` timestamp is null it gives the wrong timediff.
