### ISSUE TITLE
URL Validation Function Needs Fixes

### ISSUE THREAD

**Issue by dhextras** [wavly/shawty#44]
#### Validate URL Issues:
1. **Short URL Check**:
   - The function does not account for the `https://` prefix when checking the length of the URL, which means it would never reach min length validation checks which is 4.

2. **TLD Checking**:
   - The TLD validation is inadequate; it simply checks for a `.` in the URL, allowing invalid URLs like `https://lol/some.thing` to pass.

3. **Domain Extraction**:
   - The function incorrectly considers the path of the URL as part of the domain. Only the hostname should be extracted and validated separately.

4. **Lack of URL Sanitization**:
   - There’s no sanitization of the URL, meaning special characters are not handled correctly, like `][\@!` etc...

#### Validate Code Issues:
- Errors returned are not used by the consumers of the function nor presented to users, making it difficult to identify issue for the users and rendering the returned argumenets usless.

**Comment by Hamza12700** [comment]
> Errors returned are not used by the consumers of the function nor presented to users, making it difficult to identify issue for the users and rendering the returned argumenets usless.

No, that's wrong, errors returned by the `ValidateUrl` function call is been sent to the user: `shawty/handlers/shawty.go`
```go
func Shawty(w http.ResponseWriter, r *http.Request) {
        // code...

	// Validate the URL
	err := validate.ValidateUrl(inputUrl)
	if err != nil {
		Logger.Warn("failed to validate URL", "url", inputUrl, "user-agent", r.UserAgent(), "error", err)
		errorTempl := template.Must(template.ParseFiles("./partial-html/short-link-error.html"))
		asserts.NoErr(errorTempl.Execute(w, err), "Failed to execute template short-link-error.html")
		return
	}
}
```

**Comment by dhextras** [comment]
> > Errors returned are not used by the consumers of the function nor presented to users, making it difficult to identify issue for the users and rendering the returned argumenets usless.
> 
> No, that's wrong, errors returned by the `ValidateUrl` function call is been sent to the user: `shawty/handlers/shawty.go`
> 
> ```go
> func Shawty(w http.ResponseWriter, r *http.Request) {
>         // code...
> 
> 	// Validate the URL
> 	err := validate.ValidateUrl(inputUrl)
> 	if err != nil {
> 		Logger.Warn("failed to validate URL", "url", inputUrl, "user-agent", r.UserAgent(), "error", err)
> 		errorTempl := template.Must(template.ParseFiles("./partial-html/short-link-error.html"))
> 		asserts.NoErr(errorTempl.Execute(w, err), "Failed to execute template short-link-error.html")
> 		return
> 	}
> }
> ```

No I wan't mentioning `ValidateUrl` but rather `ValidateCode` that had the issue
![image](https://github.com/user-attachments/assets/fa4bc6a0-59df-4af7-bd83-9ea71f61efd8)

```go 
func Redirect(w http.ResponseWriter, r *http.Request) {
	code := r.PathValue("code")

	// Validate the code
	err := validate.CustomCodeValidate(code)
	if err != nil {
		Logger.Warn("Code validation failed", "code", code, "user-agent", r.UserAgent())
		http.Redirect(w, r, "/", http.StatusBadRequest)
		return
	}
```

**Comment by Hamza12700** [comment]
Sorry, @dhextras I miss read it.

The reason I decide to not send the error message to the user is because the error is only for debugging and logging purposes, showing the error of the code for the short link is invalid seems kind a wired in a normal user's perspective. So that is why I decided to not show but instead redirect the user to home page.

But if you've a good reasons about why we should send the error message for the invalid code then I'd like to hear that.

**Comment by dhextras** [comment]
> Sorry, @dhextras I miss read it.
> 
> The reason I decide to not send the error message to the user is because the error is only for debugging and logging purposes, showing the error of the code for the short link is invalid seems kind a wired in a normal user's perspective. So that is why I decided to not show but instead redirect the user to home page.
> 
> But if you've a good reasons about why we should send the error message for the invalid code then I'd like to hear that.

Im not saying we should show the error to the user when redirecting, at least log them out in the server and instead of showing the plan bad request page we should either redirect them to home page / or show the URL is not valid something like that

**Comment by Hamza12700** [comment]
> Im not saying we should show the error to the user when redirecting, at least log them out in the server and instead of showing the plain bad request page we should either redirect them to home page / or show the URL is not valid something like that

Yes, the errors are being logged when the code is invalid: `shawty/handlers/redirect.go`
```go
func Redirect(w http.ResponseWriter, r *http.Request) {
	code := r.PathValue("code")

	// Validate the code
	err := validate.CustomCodeValidate(code)
	if err != nil {
		Logger.Warn("Code validation failed", "code", code, "user-agent", r.UserAgent())
		http.Redirect(w, r, "/", http.StatusBadRequest)
		return
	}
}
```

> ... and instead of showing the plain bad request page we should either redirect them to home page / or show the URL is not valid something like that

Not sure what you mean by **plain old request page** but the other part is correct that if the code is invalid or doesn't exist then it redirects the user to the home page `/`

**Comment by dhextras** [comment]
> Not sure what you mean by **plain old request page** but the other part is correct that if the code is invalid or doesn't exist then it redirects the user to the home page `/`

I'm saying it doesn't redirect to the home page but rather just go here, which have Anchor pointed to home page
![image](https://github.com/user-attachments/assets/206ec482-3d26-44c7-b9cc-2dd21f5a8673)

2. you are not actually logging the `err` it self, just the code validation failed and not why it failed

**Comment by Hamza12700** [comment]
> you are not actually logging the err it self, just the code validation failed and not why it failed

What you mean not logging the error itself? The value that is being returned by the `validate.CustomCodeValidate` function is the error why the code validation failed. What other error are you referring to?

**Comment by Hamza12700** [comment]
> ![image](https://github.com/user-attachments/assets/26c3a57e-8ab9-4a98-a82c-b7448f3683df)

This is because of the status code. It should be `303`

**Comment by dhextras** [comment]
@Hamza12700 

![image](https://github.com/user-attachments/assets/00a0f214-d0cc-45a8-8325-37c2953d2442)
When the validation fails its logs ` Code validation failed ` which is not the err that is being returned from the function, which is one of the below error from here

![image](https://github.com/user-attachments/assets/93b547d7-d5f4-4033-a88b-2993c228268b)

**Comment by dhextras** [comment]
> > ![image](https://private-user-images.githubusercontent.com/72913359/380473614-26c3a57e-8ab9-4a98-a82c-b7448f3683df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTIwMjcsIm5iZiI6MTczMDAxMTcyNywicGF0aCI6Ii83MjkxMzM1OS8zODA0NzM2MTQtMjZjM2E1N2UtOGFiOS00YTk4LWE4MmMtYjc0NDhmMzY4M2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2NDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzJmYWU2Njc5ZTMwNTIyYzVkYWYwYTRhOTJkYWFjNWQ4YWEzNjA3NTQ4YjZmMzE5MGUwMmNiNWM4OGE1NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D6JRMRSk8XVegZZsWSQGGoPjilFAi4J0FTcNhTli3rQ)
> 
> This is because of the status code. It should be `303` not `400`

i didn't get that why would it return 400 if it's expecting to return 303. can you explain more about this ?

**Comment by Hamza12700** [comment]
> i didn't get that why would it return 400 if it's expecting to return 303. can you explain more about this ?

The server returns `400` a bad request because the code for the short link is either invalid or doesn't exist. It should return `303` in order to redirect the user to home page.

**Comment by Hamza12700** [comment]
> @Hamza12700
> 
> ![image](https://private-user-images.githubusercontent.com/104954857/380473645-00a0f214-d0cc-45a8-8325-37c2953d2442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTIxNDYsIm5iZiI6MTczMDAxMTg0NiwicGF0aCI6Ii8xMDQ5NTQ4NTcvMzgwNDczNjQ1LTAwYTBmMjE0LWQwY2MtNDVhOC04MzI1LTM3YzI5NTNkMjQ0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDJmOWZjOGYwNGZmNjE4YWZmNzkyNjNkYjdiNDE2Y2E1YjNhZGViYzJjYjlmOGYwNzdlZmZlZmU2OTQyNGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w189ZKxxfpdWysbXepuTef_2dEJg_QBuDf1VqnLY3qU) When the validation fails its logs `Code validation failed` which is not the err that is being returned from the function, which is one of the below error from here
> 
> ![image](https://private-user-images.githubusercontent.com/104954857/380473680-93b547d7-d5f4-4033-a88b-2993c228268b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTIxNDYsIm5iZiI6MTczMDAxMTg0NiwicGF0aCI6Ii8xMDQ5NTQ4NTcvMzgwNDczNjgwLTkzYjU0N2Q3LWQ1ZjQtNDAzMy1hODhiLTI5OTNjMjI4MjY4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzY4NjQwMGQ5NTY1MmYyY2U2ZDY3ZTcyMjc0YTUwZjZiOGVmOGY5MzhmNzc1NWJkMTMwZDJjM2YxYmYxZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0SX4r42LaoFwPXebA7t_QFZEfYU3E7KiIKnaIRNFVf4)

I must of forgot to add log the error too.

**Comment by dhextras** [comment]
> > @Hamza12700
> > ![image](https://private-user-images.githubusercontent.com/104954857/380473645-00a0f214-d0cc-45a8-8325-37c2953d2442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTIxNDYsIm5iZiI6MTczMDAxMTg0NiwicGF0aCI6Ii8xMDQ5NTQ4NTcvMzgwNDczNjQ1LTAwYTBmMjE0LWQwY2MtNDVhOC04MzI1LTM3YzI5NTNkMjQ0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDJmOWZjOGYwNGZmNjE4YWZmNzkyNjNkYjdiNDE2Y2E1YjNhZGViYzJjYjlmOGYwNzdlZmZlZmU2OTQyNGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w189ZKxxfpdWysbXepuTef_2dEJg_QBuDf1VqnLY3qU) When the validation fails its logs `Code validation failed` which is not the err that is being returned from the function, which is one of the below error from here
> > ![image](https://private-user-images.githubusercontent.com/104954857/380473680-93b547d7-d5f4-4033-a88b-2993c228268b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTIxNDYsIm5iZiI6MTczMDAxMTg0NiwicGF0aCI6Ii8xMDQ5NTQ4NTcvMzgwNDczNjgwLTkzYjU0N2Q3LWQ1ZjQtNDAzMy1hODhiLTI5OTNjMjI4MjY4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzY4NjQwMGQ5NTY1MmYyY2U2ZDY3ZTcyMjc0YTUwZjZiOGVmOGY5MzhmNzc1NWJkMTMwZDJjM2YxYmYxZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0SX4r42LaoFwPXebA7t_QFZEfYU3E7KiIKnaIRNFVf4)
> 
> I must of forgot to add log the error too.

yeah that's what i was refering to

**Comment by dhextras** [comment]
> > i didn't get that why would it return 400 if it's expecting to return 303. can you explain more about this ?
> 
> The server returns `400` a bad request because the code for the short link is either invalid or doesn't exist. It should return `303` in order to redirect the user to home page.

Okay I still don't understand if it's not gonna redirect to the home page y even use `StatusBadRequest` rather then something that will return in 3xx

> ```go
> http.Redirect(w, r, "/", http.StatusBadRequest)
> ```

**Comment by dhextras** [comment]
> > > i didn't get that why would it return 400 if it's expecting to return 303. can you explain more about this ?
> > 
> > 
> > The server returns `400` a bad request because the code for the short link is either invalid or doesn't exist. It should return `303` in order to redirect the user to home page.
> 
> Okay I still don't understand if it's not gonna redirect to the home page y even use `StatusBadRequest` rather then something that will return in 3xx
> 
> > ```go
> > http.Redirect(w, r, "/", http.StatusBadRequest)
> > ```

what's the point of this redirection? is it to redirect users to the home page?

**Comment by Hamza12700** [comment]
> what's the point of this redirection? is it to redirect users to the home page?

Yes, if the code is invalid or doesn't exist redirect them to the home page

**Comment by Hamza12700** [comment]
> Okay I still don't understand if it's not gonna redirect to the home page y even use StatusBadRequest rather then something that will return in 3xx

My bad, I thought because it's taking user input then if the code is invalid or doesn't exists then it should be a status bad request but doing the browser doesn't redirect the user.

**Comment by dhextras** [comment]
> Yes, if the code is invalid or doesn't exist redirect them to the home page

Then y use the status code `400` -- `StatusBadRequest` which clearly doesn't redirect

**Comment by dhextras** [comment]
> > Okay I still don't understand if it's not gonna redirect to the home page y even use StatusBadRequest rather then something that will return in 3xx
> 
> My bad, I thought because it's taking user input then if the code is invalid or doesn't exists then it should be a status bad request but doing the browser doesn't redirect the user.

Okay that's what I was asking, cool if you fixed it, what about the rest of the issue ( the validate URL part )

**Comment by Hamza12700** [comment]
> Then y use the status code 400 -- StatusBadRequest which clearly doesn't redirect

It was a mistake man. I forgot that sending a status bad request doesn't if trying to redirect.

**Comment by dhextras** [comment]
> > Then y use the status code 400 -- StatusBadRequest which clearly doesn't redirect
> 
> It was a mistake man. I forgot that sending a status bad request doesn't if trying to redirect.

LOL fine, since you were arguing I was confused haha

**Comment by Hamza12700** [comment]
> Okay that's what I was asking, cool if you fixed it, what about the rest of the issue ( the validate URL part )

The rest are all valid issues. They need to fixed.

**Comment by dhextras** [comment]
> > Okay that's what I was asking, cool if you fixed it, what about the rest of the issue ( the validate URL part )
> 
> The rest are all valid issues. They need to fixed.

Alr ill work on it

**Comment by dhextras** [comment]
> > > Then y use the status code 400 -- StatusBadRequest which clearly doesn't redirect
> > 
> > 
> > It was a mistake man. I forgot that sending a status bad request doesn't if trying to redirect.
> 
> LOL fine, since you were arguing I was confused and thought there was a reason for it haha

**Comment by Hamza12700** [comment]
> LOL fine, since you were arguing I was confused haha

What? I wasn't arguing I was just trying to explain to you what is the issue you are having.

**Comment by dhextras** [comment]
> > LOL fine, since you were arguing I was confused haha
> 
> What? I wasn't arguing I was just trying to explain to you what is the issue you are having.

lol fine man, I was just confused, and thought there might be a reason for it, Appreciate the explanation
